### PR TITLE
bump knmstate to v0.13.0

### PR DESCRIPTION
**Pull request by phoracek**
Signed-off-by: Petr Horacek <phoracek@redhat.com>

### CODE REVIEW

**Comment by phoracek** [comment]
/override pull-e2e-cluster-network-addons-operator-lifecycle-okd 
/override pull-e2e-cluster-network-addons-operator-lifecycle-workflow-okd

OKD lane is broken.

**Comment by qinqon** [comment]
So this is the diff of manifests
command `git diff v0.12.0..v0.13.0 -- deploy`
```diff
diff --git a/deploy/crds/nmstate.io_nodenetworkconfigurationenactments_crd.yaml b/deploy/crds/nmstate.io_nodenetworkconfigurationenactments_crd.yaml
new file mode 100644
index 00000000..cefeb819
--- /dev/null
+++ b/deploy/crds/nmstate.io_nodenetworkconfigurationenactments_crd.yaml
@@ -0,0 +1,70 @@
+apiVersion: apiextensions.k8s.io/v1beta1
+kind: CustomResourceDefinition
+metadata:
+  name: nodenetworkconfigurationenactments.nmstate.io
+spec:
+  group: nmstate.io
+  names:
+    kind: NodeNetworkConfigurationEnactment
+    listKind: NodeNetworkConfigurationEnactmentList
+    plural: nodenetworkconfigurationenactments
+    shortNames:
+    - nnce
+    singular: nodenetworkconfigurationenactment
+  scope: Cluster
+  subresources:
+    status: {}
+  validation:
+    openAPIV3Schema:
+      description: NodeNetworkConfigurationEnactment is the Schema for the nodenetworkconfigurationenactments
+        API
+      properties:
+        apiVersion:
+          description: 'APIVersion defines the versioned schema of this representation
+            of an object. Servers should convert recognized schemas to the latest
+            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
+          type: string
+        kind:
+          description: 'Kind is a string value representing the REST resource this
+            object represents. Servers may infer this from the endpoint the client
+            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
+          type: string
+        metadata:
+          type: object
+        status:
+          description: NodeNetworkConfigurationEnactmentStatus defines the observed
+            state of NodeNetworkConfigurationEnactment
+          properties:
+            conditions:
+              items:
+                properties:
+                  lastHearbeatTime:
+                    format: date-time
+                    type: string
+                  lastTransitionTime:
+                    format: date-time
+                    type: string
+                  message:
+                    type: string
+                  reason:
+                    type: string
+                  status:
+                    type: string
+                  type:
+                    type: string
+                required:
+                - status
+                - type
+                type: object
+              type: array
+            desiredState:
+              description: The desired state rendered for the enactment's node using
+                the policy desiredState as template
+              type: object
+          type: object
+      type: object
+  version: v1alpha1
+  versions:
+  - name: v1alpha1
+    served: true
+    storage: true
diff --git a/deploy/crds/nmstate_v1alpha1_nodenetworkconfigurationpolicy_crd.yaml b/deploy/crds/nmstate.io_nodenetworkconfigurationpolicies_crd.yaml
similarity index 64%
rename from deploy/crds/nmstate_v1alpha1_nodenetworkconfigurationpolicy_crd.yaml
rename to deploy/crds/nmstate.io_nodenetworkconfigurationpolicies_crd.yaml
index 60ff1fab..92039b05 100644
--- a/deploy/crds/nmstate_v1alpha1_nodenetworkconfigurationpolicy_crd.yaml
+++ b/deploy/crds/nmstate.io_nodenetworkconfigurationpolicies_crd.yaml
@@ -16,6 +16,8 @@ spec:
     status: {}
   validation:
     openAPIV3Schema:
+      description: NodeNetworkConfigurationPolicy is the Schema for the nodenetworkconfigurationpolicies
+        API
       properties:
         apiVersion:
           description: 'APIVersion defines the versioned schema of this representation
@@ -30,6 +32,8 @@ spec:
         metadata:
           type: object
         spec:
+          description: NodeNetworkConfigurationPolicySpec defines the desired state
+            of NodeNetworkConfigurationPolicy
           properties:
             desiredState:
               description: The desired configuration of the policy
@@ -41,14 +45,35 @@ spec:
                 policy to be applied to the node. Selector which must match a node''s
                 labels for the policy to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/'
               type: object
-            priority:
-              description: In case of multiple policies applying for the same node
-                this priority define the order from low to high
-              format: int64
-              type: integer
           type: object
         status:
+          description: NodeNetworkConfigurationPolicyStatus defines the observed state
+            of NodeNetworkConfigurationPolicy
+          properties:
+            conditions:
+              items:
+                properties:
+                  lastHearbeatTime:
+                    format: date-time
+                    type: string
+                  lastTransitionTime:
+                    format: date-time
+                    type: string
+                  message:
+                    type: string
+                  reason:
+                    type: string
+                  status:
+                    type: string
+                  type:
+                    type: string
+                required:
+                - status
+                - type
+                type: object
+              type: array
           type: object
+      type: object
   version: v1alpha1
   versions:
   - name: v1alpha1
diff --git a/deploy/crds/nmstate_v1alpha1_nodenetworkstate_crd.yaml b/deploy/crds/nmstate.io_nodenetworkstates_crd.yaml
similarity index 53%
rename from deploy/crds/nmstate_v1alpha1_nodenetworkstate_crd.yaml
rename to deploy/crds/nmstate.io_nodenetworkstates_crd.yaml
index c7c72aa3..54811d40 100644
--- a/deploy/crds/nmstate_v1alpha1_nodenetworkstate_crd.yaml
+++ b/deploy/crds/nmstate.io_nodenetworkstates_crd.yaml
@@ -16,6 +16,7 @@ spec:
     status: {}
   validation:
     openAPIV3Schema:
+      description: NodeNetworkState is the Schema for the nodenetworkstates API
       properties:
         apiVersion:
           description: 'APIVersion defines the versioned schema of this representation
@@ -29,25 +30,42 @@ spec:
           type: string
         metadata:
           type: object
-        spec:
-          properties:
-            desiredState:
-              description: The desired configuration for the node
-              type: object
-            managed:
-              type: boolean
-            nodeName:
-              description: Name of the node reporting this state
-              type: string
-          required:
-          - managed
-          - nodeName
-          type: object
         status:
+          description: NodeNetworkStateStatus is the status of the NodeNetworkState
+            of a specific node
           properties:
+            conditions:
+              items:
+                properties:
+                  lastHearbeatTime:
+                    format: date-time
+                    type: string
+                  lastTransitionTime:
+                    format: date-time
+                    type: string
+                  message:
+                    type: string
+                  reason:
+                    type: string
+                  status:
+                    type: string
+                  type:
+                    type: string
+                required:
+                - status
+                - type
+                type: object
+              type: array
             currentState:
+              description: "State contains the namestatectl yaml [1] as string instead
+                of golang struct so we don't need to be in sync with the schema. \n
+                [1] https://github.com/nmstate/nmstate/blob/master/libnmstate/schemas/operational-state.yaml"
               type: object
+            lastSuccessfulUpdateTime:
+              format: date-time
+              type: string
           type: object
+      type: object
   version: v1alpha1
   versions:
   - name: v1alpha1
diff --git a/deploy/crds/nmstate.io_v1alpha1_nodenetworkconfigurationenactment_cr.yaml b/deploy/crds/nmstate.io_v1alpha1_nodenetworkconfigurationenactment_cr.yaml
new file mode 100644
index 00000000..4c76438f
--- /dev/null
+++ b/deploy/crds/nmstate.io_v1alpha1_nodenetworkconfigurationenactment_cr.yaml
@@ -0,0 +1,32 @@
+apiVersion: nmstate.io/v1alpha1
+kind: NodeNetworkConfigurationEnactment
+metadata:
+  creationTimestamp: "2019-12-04T10:55:12Z"
+  generation: 1
+  name: node01.test-policy
+  ownerReferences:
+  - apiVersion: nmstate.io/v1alpha1
+    kind: NodeNetworkConfigurationPolicy
+    name: test-policy
+    uid: d7e35a96-6094-4b2e-a899-9ee6a5eef157
+  resourceVersion: "4682"
+  selfLink: /apis/nmstate.io/v1alpha1/nodenetworkconfigurationenactments/node01.test-policy
+  uid: 2f255a93-c2b5-43a5-a401-7184150fa9f1
+status:
+  conditions:
+  - lastHearbeatTime: "2019-12-04T10:55:32Z"
+    lastTransitionTime: "2019-12-04T10:55:32Z"
+    reason: SuccessfullyConfigured
+    status: "False"
+    type: Progressing
+  - lastHearbeatTime: "2019-12-04T10:55:32Z"
+    lastTransitionTime: "2019-12-04T10:55:32Z"
+    reason: SuccessfullyConfigured
+    status: "False"
+    type: Failing
+  - lastHearbeatTime: "2019-12-04T10:55:32Z"
+    lastTransitionTime: "2019-12-04T10:55:32Z"
+    message: successfully reconciled
+    reason: SuccessfullyConfigured
+    status: "True"
+    type: Available
diff --git a/deploy/crds/nmstate_v1alpha1_nodenetworkconfigurationpolicy_cr.yaml b/deploy/crds/nmstate.io_v1alpha1_nodenetworkconfigurationpolicy_cr.yaml
similarity index 100%
rename from deploy/crds/nmstate_v1alpha1_nodenetworkconfigurationpolicy_cr.yaml
rename to deploy/crds/nmstate.io_v1alpha1_nodenetworkconfigurationpolicy_cr.yaml
diff --git a/deploy/crds/nmstate.io_v1alpha1_nodenetworkstate_cr.yaml b/deploy/crds/nmstate.io_v1alpha1_nodenetworkstate_cr.yaml
new file mode 100644
index 00000000..57bd5486
--- /dev/null
+++ b/deploy/crds/nmstate.io_v1alpha1_nodenetworkstate_cr.yaml
@@ -0,0 +1,188 @@
+apiVersion: nmstate.io/v1alpha1
+kind: NodeNetworkState
+metadata:
+  creationTimestamp: "2019-12-03T08:31:04Z"
+  generation: 1
+  name: node01
+  ownerReferences:
+  - apiVersion: v1
+    kind: Node
+    name: node01
+    uid: d3c4563b-ece3-49a3-b0b6-81d12b112e89
+  resourceVersion: "728"
+  selfLink: /apis/nmstate.io/v1alpha1/nodenetworkstates/node01
+  uid: d8b24483-3162-44ce-a335-666844569562
+status:
+  currentState:
+    dns-resolver:
+      config:
+        search: []
+        server: []
+      running:
+        search: []
+        server:
+        - 192.168.66.2
+    interfaces:
+    - bridge:
+        options:
+          group-forward-mask: 0
+          mac-ageing-time: 300
+          multicast-snooping: true
+          stp:
+            enabled: false
+            forward-delay: 15
+            hello-time: 2
+            max-age: 20
+            priority: 32768
+        port: []
+      ipv4:
+        address:
+        - ip: 10.244.0.1
+          prefix-length: 24
+        dhcp: false
+        enabled: true
+      ipv6:
+        address:
+        - ip: fe80::5ccc:abff:fe0a:db1e
+          prefix-length: 64
+        autoconf: false
+        dhcp: false
+        enabled: true
+      mac-address: 5E:CC:AB:0A:DB:1E
+      mtu: 1450
+      name: cni0
+      state: up
+      type: linux-bridge
+    - bridge:
+        options:
+          group-forward-mask: 0
+          mac-ageing-time: 300
+          multicast-snooping: true
+          stp:
+            enabled: false
+            forward-delay: 15
+            hello-time: 2
+            max-age: 20
+            priority: 32768
+        port: []
+      ipv4:
+        address:
+        - ip: 172.17.0.1
+          prefix-length: 16
+        dhcp: false
+        enabled: true
+      ipv6:
+        autoconf: false
+        dhcp: false
+        enabled: false
+      mac-address: 02:42:DD:B5:49:60
+      mtu: 1500
+      name: docker0
+      state: up
+      type: linux-bridge
+    - ipv4:
+        address:
+        - ip: 192.168.66.101
+          prefix-length: 24
+        auto-dns: true
+        auto-gateway: true
+        auto-routes: true
+        dhcp: true
+        enabled: true
+      ipv6:
+        address:
+        - ip: fe80::5055:ff:fed1:5501
+          prefix-length: 64
+        autoconf: false
+        dhcp: false
+        enabled: true
+      mac-address: 52:55:00:D1:55:01
+      mtu: 1500
+      name: eth0
+      state: up
+      type: ethernet
+    - ipv4:
+        enabled: false
+      ipv6:
+        enabled: false
+      mac-address: 52:55:00:D1:56:00
+      mtu: 1500
+      name: eth1
+      state: down
+      type: ethernet
+    - ipv4:
+        enabled: false
+      ipv6:
+        enabled: false
+      mac-address: 52:55:00:D1:56:01
+      mtu: 1500
+      name: eth2
+      state: down
+      type: ethernet
+    - ipv4:
+        enabled: false
+      ipv6:
+        enabled: false
+      mac-address: 8A:58:1B:E1:ED:CA
+      mtu: 1450
+      name: flannel.1
+      state: down
+      type: vxlan
+      vxlan:
+        base-iface: eth0
+        destination-port: 8472
+        id: 1
+        remote: ""
+    - ipv4:
+        enabled: false
+      ipv6:
+        enabled: false
+      mtu: 65536
+      name: lo
+      state: down
+      type: unknown
+    route-rules:
+      config: []
+    routes:
+      config: []
+      running:
+      - destination: 10.244.0.0/24
+        metric: 0
+        next-hop-address: ""
+        next-hop-interface: cni0
+        table-id: 254
+      - destination: 172.17.0.0/16
+        metric: 0
+        next-hop-address: ""
+        next-hop-interface: docker0
+        table-id: 254
+      - destination: 0.0.0.0/0
+        metric: 100
+        next-hop-address: 192.168.66.2
+        next-hop-interface: eth0
+        table-id: 254
+      - destination: 192.168.66.0/24
+        metric: 100
+        next-hop-address: ""
+        next-hop-interface: eth0
+        table-id: 254
+      - destination: fe80::/64
+        metric: 256
+        next-hop-address: ""
+        next-hop-interface: cni0
+        table-id: 254
+      - destination: fe80::/64
+        metric: 100
+        next-hop-address: ""
+        next-hop-interface: eth0
+        table-id: 254
+      - destination: ff00::/8
+        metric: 256
+        next-hop-address: ""
+        next-hop-interface: cni0
+        table-id: 255
+      - destination: ff00::/8
+        metric: 256
+        next-hop-address: ""
+        next-hop-interface: eth0
+        table-id: 255
diff --git a/deploy/crds/nmstate_v1alpha1_nodenetworkstate_cr.yaml b/deploy/crds/nmstate_v1alpha1_nodenetworkstate_cr.yaml
deleted file mode 100644
index 3d642a73..00000000
--- a/deploy/crds/nmstate_v1alpha1_nodenetworkstate_cr.yaml
+++ /dev/null
@@ -1,7 +0,0 @@
-apiVersion: nmstate.io/v1alpha1
-kind: NodeNetworkState
-metadata:
-  name: example-nodenetworkstate
-spec:
-  # Add fields here
-  size: 3
diff --git a/deploy/role.yaml b/deploy/role.yaml
index e126e24d..ce76c193 100644
--- a/deploy/role.yaml
+++ b/deploy/role.yaml
@@ -15,6 +15,7 @@ rules:
   - events
   - configmaps
   - secrets
+  - pods
   verbs:
   - '*'
 - apiGroups:
@@ -59,6 +60,8 @@ rules:
   - ""
   resources:
   - nodes
+  - namespaces
   verbs:
   - get
   - list
+  - watch
```

**Comment by phoracek** [comment]
Thanks for double-checking!

**Pull request merged**
