### PR TITLE
[main] Release v0.83.1

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Release v0.83.1

Since some components takes more time to be deployed,
increase timeout.

**Special notes for your reviewer**:
See https://github.com/kubevirt/cluster-network-addons-operator/pull/1490#issuecomment-1362823690

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by oshoval** [comment]
/cc @RamLavi 
If it works, we can close either of the PRs and take the fix
Whichever you decide

**Comment by oshoval** [comment]
fails again, but now on the downgrade test IIUC
```
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1493/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1607644003249950720#1:build-log.txt%3A790
```
and no more problems as we had on the previous run with the new components

/retest

**Comment by RamLavi** [comment]
/override pull-e2e-cluster-network-addons-operator-lifecycle-k8s

This issue is important, but not relevant for this change

**Comment by oshoval** [comment]
/hold

There is a problem i think with KubeSecondaryDNS
pkg/apis/networkaddonsoperator/shared/zz_generated.deepcopy.go
doesn't include KSD

**Comment by oshoval** [comment]
/close

TO wont enter for now, lets continue on 1490

**Comment by RamLavi** [comment]
Hey @maiqueb 
is [this](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1493/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1607644003249950720#1:build-log.txt%3A2996) a problem with multus not being able to delete the linux-bridge plugin pod?
```

        Warning  FailedKillPod   20s (x138 over 29m)  kubelet            error killing pod: failed to "KillPodSandbox" for "e5b68047-e1a3-4ca0-8e75-f4a679d81e28" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for pod sandbox k8s_kube-cni-linux-bridge-plugin-zzc5x_cluster-network-addons_e5b68047-e1a3-4ca0-8e75-f4a679d81e28_0(cb3132a1263a14b65522085a744da73c41708ebc40a8fd4abb8f78527c17aada): error removing pod cluster-network-addons_kube-cni-linux-bridge-plugin-zzc5x from CNI network \"multus-cni-network\": Multus: [cluster-network-addons/kube-cni-linux-bridge-plugin-zzc5x]: error getting pod: Unauthorized"
```

It happens only on version 0.69.0 upgrading to the latest..

**Comment by maiqueb** [comment]
@RamLavi why would multus delete other pods ?

iirc, @qinqon trackled something like this on a previous multus bump. He may have some more insight.

**Pull request closed without merging**
