### PR TITLE
Release 0.58.2

### PR DESCRIPTION
**Pull request by qinqon**
Signed-off-by: Quique Llorente <ellorent@redhat.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qinqon** [comment]
Failing job can be ignored since they are not for release-0.58 branch

**Comment by phoracek** [comment]
/override pull-e2e-cluster-network-addons-operator-ovs-cni-functests
/override pull-e2e-cluster-network-addons-operator-macvtap-cni-functests
/override pull-e2e-cluster-network-addons-operator-lifecycle-k8s
/override pull-e2e-cluster-network-addons-operator-br-marker-functests
/override pull-e2e-cluster-network-addons-operator-kubemacpool-functests
/override /test pull-e2e-cluster-network-addons-operator-nmstate-functests
/override pull-cluster-network-addons-operator-unit-test
/override pull-e2e-cluster-network-addons-operator-multus-functests

**Comment by phoracek** [comment]
/override pull-e2e-cluster-network-addons-operator-ovs-cni-functests
/override pull-e2e-cluster-network-addons-operator-macvtap-cni-functests
/override pull-e2e-cluster-network-addons-operator-lifecycle-k8s
/override pull-e2e-cluster-network-addons-operator-br-marker-functests
/override pull-e2e-cluster-network-addons-operator-kubemacpool-functests
/override /test pull-e2e-cluster-network-addons-operator-nmstate-functests
/override pull-e2e-cluster-network-addons-operator-multus-functests

**Comment by phoracek** [comment]
/override pull-e2e-cluster-network-addons-operator-ovs-cni-functests
/override pull-e2e-cluster-network-addons-operator-macvtap-cni-functests
/override pull-e2e-cluster-network-addons-operator-lifecycle-k8s
/override pull-e2e-cluster-network-addons-operator-br-marker-functests
/override pull-e2e-cluster-network-addons-operator-kubemacpool-functests
/override pull-e2e-cluster-network-addons-operator-nmstate-functests
/override pull-e2e-cluster-network-addons-operator-multus-functests

**Comment by qinqon** [comment]
/override pull-e2e-cluster-network-addons-operator-workflow-k8s 
/override pull-cluster-network-addons-operator-unit-test

**Pull request merged**
