### PR TITLE
Update Dockerfile to use centos:stream9

### PR DESCRIPTION
**Pull request by machadovilaca**
Signed-off-by: João Vilaça <jvilaca@redhat.com>

**What this PR does / why we need it**:

CentOS 7 is scheduled for EOL as stated in https://wiki.centos.org/About/Product, and already exited the Full Updates phase.
Therefore this PR updates CentOS version in Dockerfile for new builds to use CentOS Stream 9, which is in the full support phase (https://www.centos.org/centos-stream/).

**Special notes for your reviewer**:

**Release note**:

```release-note
Update Dockerfile to use CentOS Stream 9
```

### CODE REVIEW

**Comment by machadovilaca** [comment]
Update was made in kubevirt/project-infra/pull/1616, should fix
/retest

**Review by phoracek — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
