### PR TITLE
vendor: Bump k8s 1.26.3

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR is bumping the k8s vendor packages to 1.26.3.
In order to do that, some packages needed to be bumped manually. 

**Special notes for your reviewer**:

**Release note**:

```release-note
bump k8s vendors to 1.26.3
```

### CODE REVIEW

**Comment by RamLavi** [comment]
@avlitman @sradco do you know why the monitoring lane is failing? I see a panic in one of the tests.

**Comment by avlitman** [comment]
> @avlitman @sradco do you know why the monitoring lane is failing? I see a panic in one of the tests.

Not sure why `cannot stat '/tmp/cnao//cluster-network-addons-operator/test_logs/e2e/workflow/*.log': No such file or directory`. adding @machadovilaca to take a look.

**Comment by RamLavi** [comment]
@machadovilaca did you have a chance to take a look?

**Comment by avlitman** [comment]
Sorry missed that for some reason, and no unfortunately I don’t know,
trying to understand 🙏🏼

**Comment by RamLavi** [comment]
/test 
pull-cluster-network-addons-operator-unit-test
/test pull-e2e-cluster-network-addons-operator-workflow-k8s
/test pull-e2e-cluster-network-addons-operator-monitoring-k8s
/test pull-e2e-cluster-network-addons-operator-lifecycle-k8s
/test pull-e2e-cluster-network-addons-operator-kubemacpool-functests
/test

**Review by qinqon — APPROVED** [review]
/lgtm
/approve

**Comment by RamLavi** [comment]
/unhold 
SonarCloud issues were not introduced in this PR

/override pull-e2e-cnao-multus-dynamic-networks-functests

**Comment by oshoval** [comment]
test/e2e/monitoring/prometheus_utils.go:        "kubevirt.io/client-go/kubecli"

if we remove this we would not need kubevirt.io/client-go anymore, as was done on OVN-K

**Pull request merged**
