### PR TITLE
Add e2e tests custom reporter

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
When CNAO CI finish there is no useful artifacts to do forensics on
them, this change add a custom ginkgo reporter that will store the CNAO
pods logs into spearate files at artifacts directory.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
/retest

kubevirt timeout on KMP tier1 tst

**Comment by qinqon** [comment]
> don't we want to add it also for teir1 automation scripts?

The tier1 test reports are from project's test suite, nothing we can do about it here, it has to be done per project at their project repo.

**Comment by qinqon** [comment]
> don't we want to add it also for teir1 automation scripts?

The tier1 test reports are from project's test suite, nothing we can do about it here, it has to be done per project at their project repo.

**Comment by qinqon** [comment]
Pod logs working fine 
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/762/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1354729732138078208/artifacts/Cluster%20Network%20Addons%20Operator%20when%20installed%20from%20master%20release%20and%20when%20NodeNetworkConfig%20with%20supported%20spec%20is%20created%20reaches%20Available%20condition%20with%20all%20containers%20using%20expected%20images_pods.log

**Comment by qinqon** [comment]
/retest 
pull-cluster-network-addons-operator-unit-test

**Comment by qinqon** [comment]
/override pull-e2e-cluster-network-addons-operator-kubemacpool-functests
not related

**Comment by qinqon** [comment]
/override pull-e2e-cluster-network-addons-operator-workflow-k8s
/override pull-e2e-cluster-network-addons-operator-nmstate-functests
Not related and I see the reports there already.

**Pull request merged**
