### PR TITLE
Release 0.43.0

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
Release 0.43.0

**Special notes for your reviewer**:

**Release note**:

```release-note
Release 0.43.0
```

### CODE REVIEW

**Comment by RamLavi** [comment]
/retest

now that #690 is merged we should pass

**Comment by qinqon** [comment]
/retest

We have reduce the number of releases to test at release PR at https://github.com/kubevirt/cluster-network-addons-operator/pull/691

**Pull request merged**
