### PR TITLE
dependabot, bump containerd CRI plugin to 1.5.13

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
bump github.com/containerd/containerd to 1.5.13 to fix dependabot
issues [0] [1].

[0] https://github.com/kubevirt/cluster-network-addons-operator/security/dependabot/40
[1] https://github.com/kubevirt/cluster-network-addons-operator/security/dependabot/41

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
retest typo
/retest

**Comment by oshoval** [comment]
/test pull-e2e-cluster-network-addons-operator-ovs-cni-functests 

problem was fixed

but the unit test seem to fail on unclean git status

**Review by oshoval — APPROVED** [review]
Thanks

Imho, it will be good next time to split please to one commit which shows the manual changes, and one that shows the result of the vendoring

**Pull request merged**
