### PR TITLE
components/multus-dynamic-networks: Pin to v0.3.4

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
multus-dynamic-networks v0.3.5 is breaking. Pin to latest successful version until the issue is resolved

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oshoval** [comment]
Typo braking - > breaking
0.3.4 did pass right ?
Thanks

/lgtm

**Comment by RamLavi** [comment]
> Typo braking - > breaking 0.3.4 did pass right ? Thanks
> 
> /lgtm

yes 0.3.4 passed. If the issue was the grpc bump, then this should clear things.

**Comment by oshoval** [comment]
please run the bump locally so it will fix the unit tests / change images

**Pull request merged**
