### PR TITLE
add porcelain to check for uncommitted changes

### PR DESCRIPTION
**Pull request by RamLavi**
Signed-off-by: Ram Lavi <ralavi@redhat.com>

**What this PR does / why we need it**:
Adds porcelain check, to make sure no generated uncommitted changes are left outside of a commit.
We also add bump-all on travis.yaml to make  sure the manifests weren't changed.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
/retest

after #477 merged this should work on travis

**Comment by RamLavi** [comment]
/hold

adding a temp commit to check failure

**Comment by RamLavi** [comment]
/unhold

working ok

**Comment by qinqon** [comment]
/lgtm

Can we exercise at different PR ?

**Pull request merged**
