### PR TITLE
[release-0.79] Fix CI regression

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Based on #1523 (see for more info)

Had to use 1.24 instead 1.25 due to this error on 1.25 during nmstate upgrade test of old versions
`policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget`

Annotate the nodes with deprecated label, because this is what KMP look for
(unless we fix it on KMP for this release and bump it here)

**Special notes for your reviewer**:
The 2 ovs-mirror failures are known and ignored.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1571/pull-e2e-cnao-ovs-cni-functests-release-0.79/1671172036954689536

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by phoracek** [comment]
@oshoval we can also ignore ovs-mirror tests in the OVS CNI suite. We should make sure that ovs-cni ones pass though

**Comment by oshoval** [comment]
> @oshoval we can also ignore ovs-mirror tests in the OVS CNI suite. We should make sure that ovs-cni ones pass though

Sure, thanks for the heads-up

**Comment by oshoval** [comment]
/retest 

will fix soon infra base image so podman socket wont happen that much

**Comment by oshoval** [comment]
/test pull-e2e-cnao-ovs-cni-functests-release-0.79
only ovs-mirror failures, lets try again to make sure we are safe

**Comment by oshoval** [comment]
Same 2 failures, just ovs-mirror so we are fine with it according the [comment](https://github.com/kubevirt/cluster-network-addons-operator/pull/1571#issuecomment-1597717506) above

**Comment by oshoval** [comment]
/cc @RamLavi 
Can you please take a look ?
Thanks

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Comment by RamLavi** [comment]
@oshoval thank you for this important fix,

**Comment by oshoval** [comment]
Thanks
Please override `pull-e2e-cnao-ovs-cni-functests-release-0.79` as Petr suggested above that we can ignore the 
ovs-mirror failures.

**Comment by RamLavi** [comment]
/override pull-e2e-cnao-ovs-cni-functests-release-0.79
The failing tests are known flakes that have nothing to do with this PR change.

**Pull request merged**
