### PR TITLE
Revert "0.65, components: Follow knmstate release branch (#1148)"

### PR DESCRIPTION
**Pull request by qinqon**
Before you click the 'Create pull request' make sure that:
- This PR introduces a single feature of fix, just one
- This PR does not leave the main branch broken
- Every commit in this PR has a commit message explaining what do you change,
  why and what is the outcome
- If your change introduces a complex concept or a change to user interaction
  with the project or the application, make sure to document it

If you don't comply with these rules, you waste your energy, time of reviewers
and cause suffering of future generations.
-->

**What this PR does / why we need it**:
This reverts commit 79bbb94b2c33e3cbdd7d6778c26cd7a6afa47edb.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by rhrazdil — APPROVED** [review]

**Comment by oshoval** [comment]
PR desc has some of the hidden help, please remove it :)

**Pull request merged**
