### PR TITLE
bump knmstate to 0.15.0

### PR DESCRIPTION
**Pull request by phoracek**
Signed-off-by: Petr Horacek <phoracek@redhat.com>

### CODE REVIEW

**Comment by phoracek** [comment]
/override pull-e2e-cluster-network-addons-operator-workflow-k8s

Failed just on the flaky test.

**Comment by phoracek** [comment]
/override pull-e2e-cluster-network-addons-operator-workflow-k8s

**Comment by phoracek** [comment]
CI failed due to the multus race, safe to ignore

**Comment by qinqon** [comment]
Pasting here manifest changes:
`$ git diff v0.14.0..v0.15.0 -- deploy/`

```diff
diff --git a/deploy/crds/nmstate.io_nodenetworkconfigurationenactments_crd.yaml b/deploy/crds/nmstate.io_nodenetworkconfigurationenactments_crd.yaml
index 7efda726..f8e8b45e 100644
--- a/deploy/crds/nmstate.io_nodenetworkconfigurationenactments_crd.yaml
+++ b/deploy/crds/nmstate.io_nodenetworkconfigurationenactments_crd.yaml
@@ -66,6 +66,11 @@ spec:
               description: The desired state rendered for the enactment's node using
                 the policy desiredState as template
               type: object
+            policyGeneration:
+              description: The generation from policy needed to check if an enactment
+                condition status belongs to the same policy version
+              format: int64
+              type: integer
           type: object
       type: object
   version: v1alpha1
diff --git a/deploy/operator.yaml b/deploy/operator.yaml
index cadf77c9..d570e2aa 100644
--- a/deploy/operator.yaml
+++ b/deploy/operator.yaml
@@ -60,6 +60,10 @@ spec:
                 configMapKeyRef:
                   name: nmstate-config
                   key: interfaces_filter
+            - name: ENABLE_PROFILER
+              value: "False"
+            - name: PROFILER_PORT
+              value: "6060"
           volumeMounts:
           - name: dbus-socket
             mountPath: /run/dbus/system_bus_socket
```

**Pull request merged**
