### PR TITLE
fix: dependency in prom-rules-verify make target

### PR DESCRIPTION
**Pull request by nestoracunablanco**
This target needs that the necessary tooling is available beforehand.

**What this PR does / why we need it**: makefile minor fixes

**Special notes for your reviewer**:

**Release note**:

```release-note NONE

```

### CODE REVIEW

**Comment by nestoracunablanco** [comment]
@RamLavi @phoracek What are your thoughts on this change? Do you require any additional modifications or clarifications?

**Comment by nestoracunablanco** [comment]
Hi @RamLavi, It seems that I'm unable to trigger the tests. Could someone else please trigger them?

**Comment by RamLavi** [comment]
/ok-to-test

@nestoracunablanco can you rebase? it would probably solve the IPAM lane issue

**Comment by nestoracunablanco** [comment]
@RamLavi, I ran the kubemacpool functional tests on my workstation, and they were successful.

Since the change pertains only to the verification of the Prometheus rules and is related to the build process (with no code modifications that could impact runtime), I do not see a connection between this change and the error.

**Comment by nestoracunablanco** [comment]
@RamLavi, based on the information I provided, do you have any issues with rerunning the **pull-e2e-cluster-network-addons-operator-kubemacpool-functests**?

**Comment by RamLavi** [comment]
/retest
seems unrelated. will open an issue separately

**Pull request merged**
