### PR TITLE
Release 0.49.0

### PR DESCRIPTION
**Pull request by phoracek**
Signed-off-by: Petr Horáček <phoracek@redhat.com>

**What this PR does / why we need it**:

Features:
* bump nmstate to v0.43.0 (#800)

Bugs:
* Remove Secret leftover checks at lifecycle test (#803)

**Special notes for your reviewer**:

This also drops some older versions from lifecycle tests, leaving only the 3 latest releases and those released under HCO.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
@qinqon should this flaky be already fixed here? 
```
NodeNetworkConfigurationPolicy bonding default interface when there is a default interface with dynamic address should successfully move default IP address on top of the bond
```

**Comment by qinqon** [comment]
> @qinqon should this flaky be already fixed here? 
> 
> ```
> 
> NodeNetworkConfigurationPolicy bonding default interface when there is a default interface with dynamic address should successfully move default IP address on top of the bond
> 
> ```

I think so, I haven't see it lately there

**Pull request merged**
