### PR TITLE
stop using beta.kubernetes.io/arch

### PR DESCRIPTION
**Pull request by pacoxu**
**What this PR does / why we need it**:
See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

**Special notes for your reviewer**:

**Release note**:

```release-note
Note
```

### CODE REVIEW

**Comment by RamLavi** [comment]
/lgtm
@qinqon can you also take a look?

**Comment by qinqon** [comment]
1.18 is old enough, since we support 3 latest releases from kubernetes.
/lgtm
/approve

**Pull request merged**
