### PR TITLE
[release 0.65] networkAddonsConfig status, Remove heartbeat

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This is a manual backport of https://github.com/kubevirt/cluster-network-addons-operator/pull/1291

**Special notes for your reviewer**:
related PRs (needed for infra purposes): https://github.com/kubevirt/cluster-network-addons-operator/pull/1311, https://github.com/kubevirt/cluster-network-addons-operator/pull/1306
**Release note**:

```release-note
Removing `LastHeartbeatTime` field from networkAddonsConfig status
```

### CODE REVIEW

**Comment by RamLavi** [comment]
/hold
Let's wait until https://github.com/kubevirt/cluster-network-addons-operator/pull/1306 is merged and I rebase

**Comment by qinqon** [comment]
@RamLavi can you rebase ?

**Comment by RamLavi** [comment]
> @RamLavi can you rebase ?

done

**Pull request merged**
