### PR TITLE
Bump kubevirtci provider 1.25

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR bumps the KUBEVIRTCI_TAG and KUBEVIRT_PROVIDER to deploy k8s-1.25

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
> Thanks
> 
> https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1523/pull-e2e-cluster-network-addons-operator-multus-functests/1640361137914515456
> 
> ```
> + /tmp/cnao//cluster-network-addons-operator/cluster/kubectl.sh apply -f -
> selecting podman as container runtime
> nmstate.nmstate.io/nmstate created
> + sleep 30
> + /tmp/cnao//cluster-network-addons-operator/cluster/kubectl.sh rollout status -w -n nmstate ds nmstate-handler
> selecting podman as container runtime
> Error from server (NotFound): daemonsets.apps "nmstate-handler" not found
> ```

@oshoval @qinqon any idea why this heppens?

> 
> Also if you want multus v3 you can install it using the new version.

I think that at very least CNAO main branch should use multusV4 (if it's not broken of course) wdyt?

**Comment by oshoval** [comment]
> @oshoval @qinqon any idea why this heppens?

Not by heart

**Comment by oshoval** [comment]
```
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nmstate-operator" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nmstate-operator" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nmstate-operator" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nmstate-operator" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/nmstate-operator created
+ cat
+ /tmp/cnao//cluster-network-addons-operator/cluster/kubectl.sh apply -f -
```

maybe because the PSA ignore namespace ?
unless it is only a warning, but worth to make sure

**Comment by oshoval** [comment]
You might also need to do something like this for kubevirt, once the cluster-up is done
https://github.com/kubevirt/kubesecondarydns/pull/58

**Comment by RamLavi** [comment]
Changed to DNM, when we fix all the lanes we could consider splitting to smaller PRs..

**Comment by RamLavi** [comment]
Update: Should pass all CI once https://github.com/kubevirt/cluster-network-addons-operator/pull/1524 is merged

@qinqon could you review?

**Comment by oshoval** [comment]
what about https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1523/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1641825865903902720 ?

**Pull request merged**
