### PR TITLE
Bump ovs to version v0.5.0

### PR DESCRIPTION
**Pull request by SchSeba**
This PR also remove the ocp image and copy the ovs-vsctl binary
directly from the ovs-cni image.

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/191)

### CODE REVIEW

**Comment by SchSeba** [comment]
the failed lane looks unrelated lets try to run it again

for reference: 
https://kubevirt-master-stdci-production.apps.ovirt.org/job/kubevirt_cluster-network-addons-operator_standard-check-pr/420/artifact/ci_build_summary.html

**Comment by SchSeba** [comment]
ci test please

**Comment by phoracek** [comment]
Let's give it another run (after rebase). But the error you shared would be solved with increased timeout, hence won't block on it.

**Comment by phoracek** [comment]
Tests passed, failing OCP was due to a short timeout.

**Pull request merged**
