### PR TITLE
Generate release manifests

### PR DESCRIPTION
**Pull request by phoracek**
This will make releasing of a new version and testing on local
cluster easier.

### CODE REVIEW

**Comment by SchSeba** [comment]
question: can you maybe use https://github.com/kubernetes-sigs/kustomize ?

**Comment by phoracek** [comment]
Maybe later if it becomes more complex. However, now with a couple of parameters, I prefer few lines of `sed` over another tool dependency (hello operator-sdk) and several yamls.

**Comment by phoracek** [comment]
@booxter @SchSeba could you please review?

**Comment by phoracek** [comment]
In order to make nesting of manifests possible (needed for SVC), we need to keep definitions in code.

**Pull request closed without merging**
