### PR TITLE
bumper, Fix update of component in components.yaml

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR fixed a bug in bumper script update to components.yaml

- **bumper, Fix update of component in components.yaml**
Currently the yaml is not really changed
as we are not updating the real items when iteration, but their copy instance.
Lets fix this by updating the real items.
Also, once the components.yaml is changed the components are reformatted.
So Let's align to the way updateComponentsYaml updates it.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
@phoracek do you think this change could break the M/S scripts or any other third part project using this? (I mainly mean to the removal of the quotes)

**Review by oshoval — COMMENTED** [review]
Please capitalize the word "fix" in the title



"This PR fixed a bug in bumper script write to components.yaml"
i would change it to updating instead of write to

"fix update of component in components.yaml
Currently the yaml is not really changed
since we don't update the correct struct, but its for loop copy."

can you explain better the last 5 words ? "but .."

**Comment by RamLavi** [comment]
> can you explain better the last 5 words ? "but .."

by `loop copy instance`, I mean that when you `i, instance := range listObject {...` then instance is only a copy of listObject[i], so if you update it, it's not really updating listObject[i]

**Comment by RamLavi** [comment]
> Please capitalize the word "fix" in the title
> 
> "This PR fixed a bug in bumper script write to components.yaml"
> i would change it to updating instead of write to

done

**Comment by oshoval** [comment]
> > can you explain better the last 5 words ? "but .."
> 
> by `loop copy instance`, I mean `instance` in this example:
> 
> ```
> i, instance := range listObject {...
> ```
> 
> Notice that when you run this loop, then `instance` is only a copy of `listObject[i]`, so if you update it, it's not really updating `listObject[i]`

Thanks, please explain it by few more words in the commit message please if possible, same as you said here.

**Comment by oshoval** [comment]
if you can align PR title with commit title please (missing first word, capital Fix)

**Comment by RamLavi** [comment]
> if you can align PR title with commit title please (missing first word, capital Fix)

Done

**Comment by RamLavi** [comment]
/hold

let's wait for @phoracek to make sure this doesn't break third party scripts

**Comment by phoracek** [comment]
It should work ok. I used pyyaml on tier2. And after your change, it is still a valid yaml.

/hold cancel

**Pull request merged**
