### PR TITLE
lifecycle, ci, Update versions tested on lifecycle ci

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR updates the automation ci to run the following:
1. on regular PRs, lifecycle will run upgrade tests on: 0.39.3, 0.44.3, 0.45.0, 0.46.0, 0.47.0, 99.0.0  - total 6
2. on release PRs lifecycle will run upgrade tests on: 0.18.0, 0.23.0, 0.27.7, 0.39.3, 0.42.0, 0.44.0, 0.44.3, 0.45.0, 0.46.0, 0.47.0, 99.0.0 - total 11
3. All other releases are removed from the repo.

- **lifecycle, ci, Remove old Releases from automation**
we want to reduce lifecycle test duration by focusing on versions
released under HCO.

- **lifecycle, test only latest versions**
Update lifecycle automation on regular PRs to run only latest
and flaky versions.

- **lifecycle, add latest stable release 0.44.3 to automation**

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
/hold
@phoracek feel free to remove this hold if you're ok with this change

**Comment by RamLavi** [comment]
FYI, lifecycle test took 59m15s (!)

**Comment by qinqon** [comment]
> FYI, lifecycle test took 59m15s (!)

Sweet

**Comment by phoracek** [comment]
/hold cancel

Awesome!

**Pull request merged**
