### PR TITLE
knmstate: Remove automation install-go

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
The prow jobs has being updated and they have go toolchain already
installed.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qinqon** [comment]
/retest

RDO hiccup
```
devel:kubic:libcontainers:stable:cri-o:1.20 (Ce 114 kB/s | 4.4 kB     00:00    
Kubernetes                                      4.9 kB/s | 1.4 kB     00:00    
Kubernetes                                      355 kB/s | 132 kB     00:00    
[MIRROR] rdo-release.rpm: Curl error (7): Couldn't connect to server for https://rdoproject.org/repos/rdo-release.rpm [Failed to connect to rdoproject.org port 443: No route to host]
[MIRROR] rdo-release.rpm: Curl error (7): Couldn't connect to server for https://rdoproject.org/repos/rdo-release.rpm [Failed to connect to rdoproject.org port 443: No route to host]
[MIRROR] rdo-release.rpm: Curl error (7): Couldn't connect to server for https://rdoproject.org/repos/rdo-release.rpm [Failed to connect to rdoproject.org port 443: No route to host]
[MIRROR] rdo-release.rpm: Curl error (7): Couldn't connect to server for https://rdoproject.org/repos/rdo-release.rpm [Failed to connect to rdoproject.org port 443: No route to host]
[FAILED] rdo-release.rpm: Curl error (7): Couldn't connect to server for https://rdoproject.org/repos/rdo-release.rpm [Failed to connect to rdoproject.org port 443: No route to host]
Curl error (7): Couldn't connect to server for https://rdoproject.org/repos/rdo-release.rpm [Failed to connect to rdoproject.org port 443: No route to host]
```

**Comment by RamLavi** [comment]
I'm not sure this is a good idea..
What if they update to a more updated golang than the one nmstate supports? 
Keeping all the cnao automations checked under the same golang version is a good thing imo

**Comment by qinqon** [comment]
> I'm not sure this is a good idea.. What if they update to a more updated golang than the one nmstate supports? Keeping all the cnao automations checked under the same golang version is a good thing imo

The `go.mod` file has `go` directive that fails if something newer not present at the go version there is introduced, golang is rectrocompatible so it should be fine, only problem would be for system installing older golang version, but golang 1.16 is not that new now and here we are using go installed a prow jobs wich are 1.16.

**Comment by qinqon** [comment]
I wil do this at nmstate bump PR.

**Pull request closed without merging**
