### PR TITLE
prometheus, Add rule for KubeMacPoolDuplicateMacsFound

### PR DESCRIPTION
**Pull request by oshoval**
`KubeMacPoolDuplicateMacsFound` will alert when duplicate mac
addresses were found by kubemacpool.

Signed-off-by: Or Shoval <oshoval@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
/cc @RamLavi 
this PR is relevant once everything is ready (but it can be reviewed meanwhile if you wish, thanks)

**Comment by oshoval** [comment]
/cc @sradco 
can you please take a look ?
thanks

**Comment by oshoval** [comment]
ready to review but need to be on hold until
https://github.com/k8snetworkplumbingwg/kubemacpool/pull/322  + bump kmp in CNAO
https://github.com/kubevirt/monitoring/pull/23
are merged

/hold

**Comment by oshoval** [comment]
Rebased and fixed wrong comment

**Comment by RamLavi** [comment]
/hold
until we branch to CNAO stable branch

**Comment by RamLavi** [comment]
@oshoval did you recheck this on CRC with latest CNAO and KMP?

**Comment by oshoval** [comment]
> @oshoval did you recheck this on CRC with latest CNAO and KMP?

Checked GUI end to end with real VMs that have conflict (as we did in the e2e tests),
not on the latest bumps, but imo we are safe, nothing major changed

**Comment by RamLavi** [comment]
> > @oshoval did you recheck this on CRC with latest CNAO and KMP?
> 
> Checked GUI end to end with real VMs that have conflict (as we did in the e2e tests),
> not on the latest bumps, but imo we are safe, nothing major changed

if you feel confident with it then I'm good. 
/approve

**Pull request merged**
