### PR TITLE
[release-0.85] bump kube-secondary-dns to v0.0.13

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Manual cherry-pick of https://github.com/kubevirt/cluster-network-addons-operator/pull/1629

**Special notes for your reviewer**:
Also includes:
git-utils: Set tag size explicitly

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
/cc @RamLavi 
note that it took few more changes of KSD, but i think we are fine https://github.com/kubevirt/kubesecondarydns/releases

**Comment by oshoval** [comment]
seems like the bug you fixed @RamLavi 
https://github.com/kubevirt/cluster-network-addons-operator/pull/1628/commits/e7b6587cb1ed14dd077bb93d36cc8be88e1cebaf
will cherry-pick it here

**Comment by oshoval** [comment]
@phoracek 
we can override ovs-mirror failing on release-0.85 right ?

**Comment by phoracek** [comment]
I'm ok with us overriding mirroring tests (or always skipping them on CNAO FWIW) on all branches

**Comment by oshoval** [comment]
> I'm ok with us overriding mirroring tests (or always skipping them on CNAO FWIW) on all branches

thanks, also main included ?

**Comment by phoracek** [comment]
Yeah, main too.

**Comment by phoracek** [comment]
/override pull-e2e-cnao-workflow-k8s-release-0.85
/override pull-e2e-cnao-ovs-cni-functests-release-0.85
/override pull-e2e-cnao-multus-dynamic-networks-functests-release-0.85
/override pull-e2e-cnao-monitoring-k8s-release-0.85
/override pull-e2e-cnao-macvtap-cni-functests-release-0.85
/override pull-e2e-cnao-lifecycle-k8s-release-0.85
/override pull-e2e-cnao-kubemacpool-functests-release-0.85
/override pull-e2e-cnao-kube-secondary-dns-functests-release-0.85
/override pull-e2e-cnao-br-marker-functests-release-0.85

All lanes have passed before the accidental close

**Pull request merged**
