### PR TITLE
Bump kubernetes-nmstate to v0.29.0

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note
Bump knmstate to v0.29.0
```

### CODE REVIEW

**Comment by qinqon** [comment]
/retest

Container was not pushed yet I think

**Comment by phoracek** [comment]
@qinqon 

```
               message: 'failed to render: failed to render nmstate state handler manifests:
                error rendering manifests: failed to render manifest data/nmstate/operator.yaml:
                template: data/nmstate/operator.yaml:62:24: executing "data/nmstate/operator.yaml"
                at <.CARotateInterval>: map has no entry for key "CARotateInterval"' 
```

**Review by phoracek — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
