### PR TITLE
kubevirtci: Bump to k8s-1.23

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
CNAO is testing towards k8s-1.21 we should go to the latest k8s version
at main.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qinqon** [comment]
We need a bump with the latest ovs-cni since it contains fixes to use it with latest kubevirtci

**Review by rhrazdil — APPROVED** [review]

**Pull request merged**
