### PR TITLE
Release 0.42.0

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
Release 0.42.0

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qinqon** [comment]
/hold
I see v1alpha1 at cluster-network-addons-operator.0.42.0.clusterserviceversion.yaml

**Comment by RamLavi** [comment]
> I see v1alpha1 at cluster-network-addons-operator.0.42.0.clusterserviceversion.yaml

do you mean `operators.coreos.com/v1alpha1`?
I'm currently bumping it to v1 in #524 (first commit) - but is it necessary?

**Comment by phoracek** [comment]
We merged couple of the placement PRs. Maybe we could just wait with the release until the end of the week where we hopefully get all of them out?

**Comment by qinqon** [comment]
@phoracek ack

**Pull request closed without merging**
