### PR TITLE
Add common labels into alert definitions

### PR DESCRIPTION
**Pull request by assafad**
**What this PR does / why we need it**:
We want to be able to list all kubevirt alerts so we added labels to differentiate them.

Signed-off-by: assafad aadmi@redhat.com

**Release note**:

```release-note
Added common labels into alert definitions
```

### CODE REVIEW

**Comment by sradco** [comment]
@assaf-admi Please add constants and use them for the labels values.

**Comment by RamLavi** [comment]
Hey @assaf-admi 
your second commit `Deleted unnecessary blank line` is without signing, so the dco part is failing. could you please sign that as well?

Also, I think you need to also add the labels to the prometheus unit-tests on `hack/prom-rule-ci/prom-rules-tests.yaml` so that the expected labels match (see [here](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1097/pull-cluster-network-addons-operator-unit-test/1465237231047282688#1:build-log.txt%3A9784))
```

**Comment by RamLavi** [comment]
failed lane does not seem related to change.

/override pull-e2e-cluster-network-addons-operator-nmstate-functests

**Comment by RamLavi** [comment]
@sradco waiting on your lgtm to approve this

**Pull request merged**
