### PR TITLE
Sync uses KUBEVIRT_PROVIDER not CLUSTER_PROVIDER

### PR DESCRIPTION
**Pull request by qinqon**
Fix upstream ci to test stdci at opensthift

### CODE REVIEW

**Comment by qinqon** [comment]
@phoracek and this ?

**Comment by phoracek** [comment]
@qinqon we should fix the rest to use CLUSTER_PROVIDER as well, this has nothing to do with KubeVirt (if something, then kubevirtci, but I'm still in favor of cluster)

**Comment by phoracek** [comment]
But what is broken exactly?

**Comment by qinqon** [comment]
@phoracek I saw something wrong at k8s-nmstate so I translate it to addons, but we can discard this.

**Comment by phoracek** [comment]
We use CLUSTER_PROVIDER everywhere in this project. I don't think this is a bug, but feel free to reopen.

**Pull request closed without merging**
