### PR TITLE
KSD: Bump to v0.0.10

### PR DESCRIPTION
**Pull request by AlonaKaplan**
**What this PR does / why we need it**:
KSD: Bump to v0.0.10

**Special notes for your reviewer**:

**Release note**:

```release-note
bump ksd to v0.0.10
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks
Maybe worth to split to two commits but no biggie.
We can now also improve the automation to include it if needed.

**Comment by AlonaKaplan** [comment]
> @AlonaKaplan do you want to merge this?
@RamLavi  yes

**Comment by oshoval** [comment]
@RamLavi 
We are still using 1.23 
We should bump please imo

**Pull request merged**
