### PR TITLE
Fix ocp make cluster-sync

### PR DESCRIPTION
**Pull request by oshoval**
Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
wokflow failure here is the one that master clean has as well

**Comment by phoracek** [comment]
It fails with `message: Expected DaemonSet "cluster-network-addons/bridge-marker" does not exist`. I have not seen that on master.

**Comment by oshoval** [comment]
> It fails with `message: Expected DaemonSet "cluster-network-addons/bridge-marker" does not exist`. I have not seen that on master.

there is timeout there
    [91mTimed out after 900.219s.
the test is the same one that is failing right ?

i can remove the bump if needed (and use it just for my testing locally), but i dont think this is what caused it, but that the test is unstable, rest of the code in this PR is 2 lines about ocp /okd which arent affecting the tests

**Comment by phoracek** [comment]
The timeout happened due to a different issue. On master it is due to Multus. I'm not aware of any other component failing.

Please drop the bump.

**Comment by oshoval** [comment]
test done, looks like master i think ?

**Comment by phoracek** [comment]
/override pull-e2e-cluster-network-addons-operator-workflow-k8s

**Pull request merged**
