### PR TITLE
macvtap, release-0.53, Bump to version 0.5.0

### PR DESCRIPTION
**Pull request by oshoval**
See https://github.com/kubevirt/macvtap-cni/releases/tag/v0.5.0

Signed-off-by: Or Shoval <oshoval@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
@maiqueb

**Comment by oshoval** [comment]
@RamLavi

**Comment by RamLavi** [comment]
@oshoval you need to also run `make bump-macvtap-cni`

**Comment by oshoval** [comment]
> @oshoval you need to also run `make bump-macvtap-cni`
Yep done thanks

**Comment by oshoval** [comment]
doesnt seem related (according job scope and PR scope)

/retest

**Comment by oshoval** [comment]
/test pull-e2e-cnao-nmstate-functests-release-0.53 


pull-e2e-cnao-nmstate-functests-release-0.53 doesnt deploy macvtap, which is the only thing changed by this PR
(correct me if i am wrong please)

**Pull request merged**
