### PR TITLE
Typo fix in README

### PR DESCRIPTION
**Pull request by zcahana**
**What this PR does / why we need it**:

Fixes a typo in the README (`mavtap` --> `macvtap`).

### CODE REVIEW

**Comment by rhrazdil** [comment]
Thanks! Please sign the commit (git commit -s --amend)

**Comment by RamLavi** [comment]
@zcahana thanks for your contribution :) 

as dco check is failing, please be sure to sign the commit, by amending your commit with `-s` flag: `git commit -s --amend`, and repush

**Comment by zcahana** [comment]
thanks @rhrazdil and @RamLavi. Will sign in a couple of minutes (I submitted the fix via the GitHub UI which doesn't offer that flexibility yet :-) ).

**Pull request merged**
