### PR TITLE
tier1, Add macvtap tier1 automation test

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This script runs macvtap e2e test on CNAO cluster

**Special notes for your reviewer**:
This PR depends on [macvtap PR](https://github.com/kubevirt/macvtap-cni/pull/32) changes to be merged first
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
/hold

until [macvtap PR](https://github.com/kubevirt/macvtap-cni/pull/32) gets merged

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
