### PR TITLE
Add all the components to master release

### PR DESCRIPTION
**Pull request by SchSeba**
This PR add nmstate and ovs for the life cycle tests.

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/211)

### CODE REVIEW

**Comment by SchSeba** [comment]
I need to check the life cycle test looks like there is an issue deploying new components

/hold

**Comment by phoracek** [comment]
yeah, it's possible the test doesn't handle it well, it was never tested to add a new one

**Comment by phoracek** [comment]
Passed changed lifecycle tests.

**Pull request merged**
