### PR TITLE
add pod description to CNAO pod

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR adds pod description to CNAO pod

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by phoracek — CHANGES_REQUESTED** [review]
Let's only keep Kubernetes, drop OpenShift.

OpenShift is Kubernetes.

**Comment by phoracek** [comment]
And while doing it, would you fix the README too?

**Comment by RamLavi** [comment]
> And while doing it, would you fix the README too?

#630

**Comment by RamLavi** [comment]
> Let's only keep Kubernetes, drop OpenShift.
> 
> OpenShift is Kubernetes.

Done

**Comment by RamLavi** [comment]
> Let's only keep Kubernetes, drop OpenShift.
> 
> OpenShift is Kubernetes.

DONE

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

Thanks

**Pull request merged**
