### PR TITLE
go.mod: Bump go version to 1.19

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR is bumping the go.mod go version to 1.19

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]

**Comment by oshoval** [comment]
you ran 
make vendor right ?
locally it fails, making sure it is just my setup (i have go 1.19)

```
$ make vendor
/root/go/src/github.com/kubevirt/cluster-network-addons-operator/build/_output/bin//go//bin//go mod tidy -compat=1.19
invalid value "1.19" for flag -compat: maximum supported Go version is 1.17
usage: go mod tidy [-e] [-v] [-go=version] [-compat=version]
Run 'go help mod tidy' for details.
make: *** [Makefile:202: vendor] Error 2
```

**Comment by RamLavi** [comment]
> you ran `make vendor` ? locally it fails, making sure it is just my setup (i have go 1.19) it might be because this flag is indeed deprecated ? also shows we need to consider adding it to unit tests
> 
> ```
> $ make vendor
> /root/go/src/github.com/kubevirt/cluster-network-addons-operator/build/_output/bin//go//bin//go mod tidy -compat=1.19
> invalid value "1.19" for flag -compat: maximum supported Go version is 1.17
> usage: go mod tidy [-e] [-v] [-go=version] [-compat=version]
> Run 'go help mod tidy' for details.
> make: *** [Makefile:202: vendor] Error 2
> ```
> 
> ```
> $ go version
> go version go1.19.4 linux/amd64
> ```
> 
> maybe will help https://go.dev/doc/go1.17#go-command

you need to remove the local installation of the vendored go 
```
rm -rf build/_output/
make vendor
```

**Pull request merged**
