### PR TITLE
[release 0.53] bump kubevirtci and k8s 1.21

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR bumps KUBRVIRTCI_TAG and KUBEVIRT_PROVIDER to the correct k8s provider
Also, from this kubrvirtci bump there is no need to install a specific networkManager on cluster-up, as the version in kubevirtci is good enough.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by qinqon — APPROVED** [review]
/lgtm
/approve

**Comment by RamLavi** [comment]
/retest
prow is back but still hangs

**Comment by RamLavi** [comment]
/override pull-e2e-cnao-br-marker-functests-release-0.53 
fail seems to be irrelevant to this PR

**Pull request closed without merging**
