### PR TITLE
makefile: Add missing component to bump-all target

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
This way it will be checked as part of the unit test lane that runs the bump-all target.

**Special notes for your reviewer**:
We need to support auto detection imo.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Comment by maiqueb** [comment]
What do the unit tests have to do w/ make bump ?

**Comment by oshoval** [comment]
> What do the unit tests have to do w/ make bump ?

It is in this lane
`automation/check-patch.unit-test.sh:    make bump-all`
After it, it runs `hack/check.sh` which checks `git status` is clean

**Pull request merged**
