### PR TITLE
Nominate Or Shoval for the maintainer role

### PR DESCRIPTION
**Pull request by phoracek**
**What this PR does / why we need it**:

I would like to nominate Or Shoval for the role of CNAO maintainer. Or has been consistently contributing to the project since 2020 and he has been a de facto maintainer for some time now.

Some of his recent contributions were licensing compliance, RBAC audit, or placement API.

Or is also caring for the integration of our adjacent project into CNAO. He understands how CNAO fits into HCO and how it is registered in project-infra. He is an active contributor of kubevirtci which we use to power CNAO's CI.

In the past few months, we have been working closely together, covering all the maintainer duties and I'm fully confident in him taking the responsibility over CNAO.

**Special notes for your reviewer**:

CC @RamLavi @qinqon @oshoval 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qinqon** [comment]
/lgtm

@RamLavi can you also approve if you are ok ?

**Comment by RamLavi** [comment]
/lgtm
totally!

**Comment by phoracek** [comment]
/approve

Thanks all. Good luck Or!

**Comment by oshoval** [comment]
Thanks all

**Pull request merged**
