### PR TITLE
Update linux-bridge component

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
Update the linux-bridge component to latest in order to bridge the latest changes of bridge CNI that include the new `disableContainerInterface` option https://github.com/containernetworking/plugins/pull/997 

**Special notes for your reviewer**:
Since there is no tagged version of container network plugins yet, consume that latest version from main branch  https://github.com/containernetworking/plugins/commit/14bdce598f9d332303c375c35719c4a158f1e7db

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ormergi** [comment]
Verified on local env with latest Kubevirt, the correct bridge CNI is build and deployed by CNAO.
To verify the right bridge CNI version is deployed, I created a net-attach-def with the following net conf:
```
{   
              "type": "bridge",
              "bridge": "cryptbr",
              "disableContainerInterface": true,
              "ipam": {
                "type": "host-local",
                "subnet": "10.0.0.0/24"
              }
          }
```
The VM is fail to create as expected because its not possible to set both `IPAM` and `disableContainerInterface`:
```
ERRORED: error configuring pod [default/virt-launcher-app-srv1-bzvxw] networking: [default/virt-launcher-app-srv1-bzvxw/9c0687bd-a78d-4239-8cf2-36717e9e2f6a:supersecretnet]: error adding container to network "supersecretnet": plugin type="bridge" failed (add): cannot use IPAM when DisableContainerInterface flag is set
```

**Review by RamLavi — COMMENTED** [review]
Hey @ormergi 
Moving the update strategy to "static" is less preferable.
Can you explain why you need this `disableContainerInterface` option?
Is this change urgent? If not, can you try and reach out to https://github.com/containernetworking/plugins maintainers and kindly ask them to issue a release?

**Comment by ormergi** [comment]
> Hey @ormergi Moving the update strategy to "static" is less preferable. Can you explain why you need this `disableContainerInterface` option? Is this change urgent? If not, can you try and reach out to https://github.com/containernetworking/plugins maintainers and kindly ask them to issue a release?

Hi @RamLavi, thanks for looking at this :slightly_smiling_face: 
We need that latest version in order to have it deployed by CNAO on kubevirt CI, to address this Kubevirt bug https://issues.redhat.com/browse/CNV-28040
The gist of it is that the migration destination pod interface advertises about its existence before the migration is completed, causing traffic distortion during migration.

I am in touch with https://github.com/containernetworking/plugins maintainers and we will have it released eventually, once we do, I will post a PR to set CNAO to use the tagged version.
The PR is to address the intermediate state where we need the new bits

**Comment by RamLavi** [comment]
> > Hey @ormergi Moving the update strategy to "static" is less preferable. Can you explain why you need this `disableContainerInterface` option? Is this change urgent? If not, can you try and reach out to https://github.com/containernetworking/plugins maintainers and kindly ask them to issue a release?
> 
> Hi @RamLavi, thanks for looking at this 🙂 We need that latest version in order to have it deployed by CNAO on kubevirt CI, to address this Kubevirt bug https://issues.redhat.com/browse/CNV-28040 The gist of it is that the migration destination pod interface advertises about its existence before the migration is completed, causing traffic distortion during migration. The latest bridge CNI bits together with kubevirt latest main solve this issue.
> 
> I am in touch with https://github.com/containernetworking/plugins maintainers and we will have it released eventually, once we do, I will post a PR to set CNAO to use the tagged version. The PR is to address the intermediate state where we need the new bits

I'm totally down with that. Please remember to set it back to tagged when a new tag is available.

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
