### PR TITLE
Release 0.56.0

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
Release 0.56.0

**Special notes for your reviewer**:

**Release note**:

```release-note
Release 0.56.0
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks

**Comment by oshoval** [comment]
Maybe worth to add the change list also to the PR desc ?
```
0.56.0
* Add relationship labels to all directly deployed components (#846)
* bump ovs-cni to v0.20.0 (#870)
```

**Comment by oshoval** [comment]
error: unable to read URL "https://github.com/kubevirt/kubevirt/releases/download/v0.42.0/kubevirt-operator.yaml", server reported 404 Not Found, status code=404

**Comment by davidvossel** [comment]
> error: unable to read URL "https://github.com/kubevirt/kubevirt/releases/download/v0.42.0/kubevirt-operator.yaml", server reported 404 Not Found, status code=404

bummer, we'll release a 0.42.1. There was an issue wiht the asset generation that is being sorted out now. https://github.com/kubevirt/kubevirt/pull/5794

**Pull request merged**
