### PR TITLE
Release 0.21.0

### PR DESCRIPTION
**Pull request by qinqon**

### CODE REVIEW

**Comment by SchSeba** [comment]
ci test please

**Comment by qinqon** [comment]
I have to check if this can be related to limits change:

```yaml
          conditions:
          - type: Available
            status: "False"
            lastupdatetime: "2019-11-19T19:12:44Z"
            lasttransitiontime: "2019-11-19T19:12:44Z"
            reason: MinimumReplicasUnavailable
            message: Deployment does not have minimum availability.
          - type: Progressing
            status: "False"
            lastupdatetime: "2019-11-19T19:22:45Z"
            lasttransitiontime: "2019-11-19T19:22:45Z"
            reason: ProgressDeadlineExceeded
            message: ReplicaSet "cluster-network-addons-operator-dcfbcff88" has timed out
              progressing.
          collisioncount: null
        
```

**Comment by qinqon** [comment]
ci test please

**Comment by SchSeba** [comment]
This is a know issue in the CI we need to fix that but unrelated to this PR

**Pull request merged**
