### PR TITLE
Remove trailing spaces from CRD

### PR DESCRIPTION
**Pull request by phoracek**
**What this PR does / why we need it**:

With the current code, generated CRD would contain trailing spaces and
that would fail release unit tests lane.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by rhrazdil — APPROVED** [review]
Thanks!

**Comment by rhrazdil** [comment]
How come it didn't fail unit test before? IIUC, it should run make check as well

**Comment by phoracek** [comment]
Aha! It may be because of humans run `make` before pushing, which in turn removes whitespace https://github.com/kubevirt/cluster-network-addons-operator/blob/main/Makefile#L80. The bot drafting the release PR is not calling that?

**Pull request merged**
