### PR TITLE
Update metric names to fit metrics naming conventions

### PR DESCRIPTION
**Pull request by avlitman**
**What this PR does / why we need it**:
This fix updated metrics names to meet the metrics naming conventions. The old metrics names will not be available after this fix.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubevirt/cluster-network-addons-operator/issues/1579
Jirta-ticket: https://issues.redhat.com/browse/CNV-30515
bugzilla-bug: https://bugzilla.redhat.com/show_bug.cgi?id=2219144

**Special notes for your reviewer**:
Need to make sure all places with the old metrics names updated including docs.

**Release note**:

```
Deprecation notice for the metrics listed in the PR. They will be removed in this release. Please update your systems to use the new metrics names.

kubevirt_cnao_cr_kubemacpool_deployed_total -> kubevirt_cnao_cr_kubemacpool_aggregated
kubevirt_cnao_kubemacpool_manager_num_up_pods_total -> kubevirt_cnao_kubemacpool_manager_up
kubevirt_cnao_num_up_operators -> kubevirt_cnao_operator_up
kubevirt_kubemacpool_duplicate_macs_total -> kubevirt_cnao_kubemacpool_duplicate_macs

```

### CODE REVIEW

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Comment by avlitman** [comment]
Hi @rhrazdil @qinqon @phoracek Do we need to cherry-pick this change in order to be part of 4.14?

**Comment by phoracek** [comment]
@avlitman we don't have a stable branch yet, so you don't have to backport (there is nowhere to backport to).

**Pull request merged**
