### PR TITLE
update default provider to k8s 1.21

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR updates the KBUEVIRTCI_TAG and updated the default provider to k8s-1.21

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
looks like the [installed](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/cluster/up.sh#L35) `openvswitch` is not working well with the updated `KUBEVIRTCI_TAG` 
I tried to use a later openvswitch version but it's missing `librte` install which I didn't find yet:
```
Error: 
 Problem: conflicting requests
  - nothing provides librte_acl.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_bitratestats.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_bus_pci.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_bus_vdev.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_cfgfile.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_cmdline.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_cryptodev.so.4()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_distributor.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_eal.so.6()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_eal.so.6(DPDK_2.0)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_efd.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_ethdev.so.8()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_ethdev.so.8(DPDK_16.07)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_ethdev.so.8(DPDK_17.05)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_ethdev.so.8(DPDK_2.2)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_eventdev.so.3()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_flow_classify.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_gro.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_gso.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_hash.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_ip_frag.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_jobstats.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_kvargs.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_latencystats.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_lpm.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_mbuf.so.3()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_mbuf.so.3(DPDK_2.1)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_member.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_mempool.so.3()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_mempool.so.3(DPDK_16.07)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_mempool.so.3(DPDK_2.0)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_mempool_octeontx.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_mempool_ring.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_mempool_stack.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_meter.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_meter.so.1(DPDK_2.0)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_metrics.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_net.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pci.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pdump.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pipeline.so.3()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_bnxt.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_e1000.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_enic.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_failsafe.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_i40e.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_ixgbe.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_mlx4.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_mlx5.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_nfp.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_qede.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_ring.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_ring.so.2(DPDK_2.0)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_softnic.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_vhost.so.2()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_pmd_virtio.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_port.so.3()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_power.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_reorder.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_ring.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_ring.so.1(DPDK_2.0)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_sched.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_security.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_table.so.3()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_timer.so.1()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_vhost.so.4()(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_vhost.so.4(DPDK_16.07)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_vhost.so.4(DPDK_17.05)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_vhost.so.4(DPDK_2.0)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
  - nothing provides librte_vhost.so.4(DPDK_2.1)(64bit) needed by openvswitch-1:2.9.3-1.el7.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by RamLavi** [comment]
added a [PR](https://github.com/kubevirt/bridge-marker/pull/34) to fix the issue causing the bridge-marker tier1 test to fail

**Comment by RamLavi** [comment]
@qinqon do you think the [failed knmstate tier1 test](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/923/pull-e2e-cluster-network-addons-operator-br-marker-functests/1413038532913532928) is related to the changes is this PR?

**Review by oshoval — APPROVED** [review]

**Pull request merged**
