### PR TITLE
bumper, Adapt nmstate bump script to comply with components.yaml name

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
currently nmstate bump script is called bump-knmstate.sh
Let's change it to bump-nmstate.sh to comply with
components.yaml.
This way it's would be easier to call this script from the bumper script.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — COMMENTED** [review]
please consider changing the name on more places, if needed
https://github.com/kubevirt/cluster-network-addons-operator/search?q=knmstate

**Comment by oshoval** [comment]
commit title, please capitalize the first word (fix),
i would also change it to Adapt instead of fix

**Comment by RamLavi** [comment]
> please consider changing the name on more places, if needed
> https://github.com/kubevirt/cluster-network-addons-operator/search?q=knmstate

thank you, but no need

**Comment by RamLavi** [comment]
> commit title, please capitalize the first word (fix),
> i would also change it to Adapt instead of fix

done

**Comment by oshoval** [comment]
commit itself, miss the word bumper, and the adapt is still not capitalize ;]

**Comment by RamLavi** [comment]
> commit itself, miss the word bumper, and the adapt is still not capitalize ;]

Done

**Pull request merged**
