### PR TITLE
bump-multus, Fix ds location

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR fixed bump-multus script due to changes made on multus repo

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Nice, thanks

**Review by maiqueb — APPROVED** [review]

**Comment by maiqueb** [comment]
Does this merit a release note ?

**Comment by RamLavi** [comment]
> Does this merit a release note ?

nah, nothing changed on multus manifest (only where we take it from), so nobody should care..

**Comment by RamLavi** [comment]
Note that `pull-cluster-network-addons-operator-unit-test` is failing cause it also runs the bump scripts, and  currently multus is pointing to the old [commit](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/components.yaml#L31). 
I think I'll override in order for the bump to pass successfully. 
What do you think?

**Comment by oshoval** [comment]
> Note that `pull-cluster-network-addons-operator-unit-test` is failing cause it also runs the bump scripts, and currently multus is pointing to the old [commit](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/components.yaml#L31). I think I'll override in order for the bump to pass successfully. What do you think?

sgtm

**Pull request merged**
