### PR TITLE
git actions, ipam: Add logs collecting upon e2e errors

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Ease debugging of IPAM CI errors.
Also collect logs when running locally, even after the temp folder is deleted.

**Special notes for your reviewer**:
Injected an error to check it works, example
https://github.com/kubevirt/cluster-network-addons-operator/actions/runs/10453035964?pr=1876

Created in order to find issues such as https://github.com/kubevirt/cluster-network-addons-operator/issues/1857

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
/cc @maiqueb 
Can you please review ?
Thanks

**Comment by oshoval** [comment]
/hold

will fix
when no error, it failed ;]

cp: cannot stat '/tmp/deploy.kubevirt-ipam-controller.Sd83/github.com/kubevirt/ipam-extensions/test/e2e/.output/*.log': No such file or directory

**Comment by oshoval** [comment]
/hold cancel

fixed

**Review by maiqueb — APPROVED** [review]

**Comment by oshoval** [comment]
Thanks

/approve

**Pull request merged**
