### PR TITLE
WIP check main branch state

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by oshoval** [comment]
@RamLavi 
KMP is broken can you please take a look ?

cc @ashokpariya0

**Comment by oshoval** [comment]
all the other lanes fails also due to that it seems

**Comment by RamLavi** [comment]
should work now
/retest

**Comment by ashokpariya0** [comment]
> should work now /retest

No, It will not work, we need to merge this pr: https://github.com/kubevirt/cluster-network-addons-operator/pull/1945

**Comment by oshoval** [comment]
rest of the line might, just not ipam
step by step ;]

**Comment by oshoval** [comment]
first time i see this error seems it affect now

error applying manifest configmaps "grafana-dashboard-prometheus" already exists

**Comment by ashokpariya0** [comment]
for multus func tests are also failing with below error:

/tmp/cnao//cluster-network-addons-operator/cluster/kubectl.sh apply -f -
selecting podman as container runtime
nmstate.nmstate.io/nmstate created
+ sleep 30
+ /tmp/cnao//cluster-network-addons-operator/cluster/kubectl.sh rollout status -w -n nmstate ds nmstate-handler
selecting podman as container runtime
**Error from server (NotFound): daemonsets.apps "nmstate-handler" not found**
+ teardown
+ rm -rf /tmp/deploy.multus.Xe5a/github.com/k8snetworkplumbingwg/multus-cni
+ cd /tmp/cnao//cluster-network-addons-operator
+ make cluster-down

**Comment by oshoval** [comment]
/test pull-e2e-cluster-network-addons-operator-multus-functests
lets see if it is gone, worth to try and update nmstate

**Comment by oshoval** [comment]
merged ipam fix
thanks
https://github.com/kubevirt/cluster-network-addons-operator/pull/1945

**Comment by oshoval** [comment]
ah need to rebase for git actions
will try soon, waiting to see the other lanes first

**Comment by oshoval** [comment]
kmp related passed
thx

**Pull request closed without merging**
