### PR TITLE
ipam: Reduce git actions noise

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
When kubevirt-bot creates PRs, it will trigger the IPAM lane twice, because both
`push` and `pull_request` events occur (the bot creates a branch on main, hence `push` event happens).
The IPAM lane also runs after a PR is merged, because it triggers `push`.
In order to reduce this noise, lets remove the `push` event.
The `pull_request` is enough as long as PRs are used 
(and not direct pushes which aren't encouraged, nor monitored anyhow).

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
Opening the PR did trigger it, lets try to push changes

**Comment by oshoval** [comment]
pushing changes also worked

**Comment by oshoval** [comment]
lets check if close open trigger the jobs
notes - git actions doesnt rebase so it basically aint as important, but still good to have
(we can fix the auto rebase later)

**Comment by oshoval** [comment]
it triggered upon reopen - we are good in this aspect

**Review by maiqueb — APPROVED** [review]

**Comment by oshoval** [comment]
Thank you

/approve

**Pull request merged**
