### PR TITLE
monitoring, e2e, Move endpoints test to monitoring lane

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR syntactically moves the test as is to the monitoring lane

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
/retest
looks like lane is failing because one of the containers is not ready. Maybe it's related to recent prow issues.

**Review by rhrazdil — APPROVED** [review]

**Pull request merged**
