### PR TITLE
KSD: Bump to v0.0.9

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
See https://github.com/kubevirt/kubesecondarydns/releases/tag/v0.0.9

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
/retest 

known cluster-up flake

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Comment by oshoval** [comment]
Thanks Ram

**Comment by oshoval** [comment]
Can you please create a patch release ?

**Pull request merged**
