### PR TITLE
automation: Add STDCI

### PR DESCRIPTION
**Pull request by gbenhaim**
Signed-off-by: gbenhaim <galbh2@gmail.com>

### CODE REVIEW

**Comment by phoracek** [comment]
ci test please

**Comment by phoracek** [comment]
@gbenhaim thanks a lot. I added kubevirt webhooks to this repo, but it seems that it doesn't work

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by gbenhaim** [comment]
ci test please

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by gbenhaim** [comment]
Does `ovirt-infra ` user has write permissions to this user? 
It currently fails to report back the status because of permissions: https://kubevirt-master-stdci-production.apps.ovirt.org/job/kubevirt_cluster-network-addons-operator_standard-check-pr/19/console

**Comment by phoracek** [comment]
ci test please

**Comment by phoracek** [comment]
@gbenhaim you are right! Fixed now. Thanks for the help

**Pull request merged**
