### PR TITLE
[release-0.76] components.yaml, statify components on release-0.76

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR changes components to not follow relevant stable branches, and where there
is no stable branch, set to static.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qinqon** [comment]
/lgtm
/approve
/hold
Wait for CI jobs to merge and run

**Comment by RamLavi** [comment]
ci lanes look good
/unhold

**Comment by RamLavi** [comment]
/override pull-e2e-cnao-nmstate-functests-release-0.76 (fixed on https://github.com/kubevirt/project-infra/pull/2100)

**Comment by RamLavi** [comment]
/override pull-e2e-cnao-nmstate-functests-release-0.76 
(fixed on https://github.com/kubevirt/project-infra/pull/2100)

**Pull request merged**
