### PR TITLE
components: Consume CNI Bridge with macspoofchk support

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

As an intermediate and temporary step, consume the changes posted to the
CNI bridge [1].

Once the PR is merged into the original repo, this change will be
reverted.

In case the PR will not be merged into the original repo, we will
proceed with a more formal resolution.

[1] https://github.com/containernetworking/plugins/pull/639

**Special notes for your reviewer**:

**Release note**:

```release-note
Consume CNI Bridge with mac-spoof-check support.
```

### CODE REVIEW

**Comment by EdDev** [comment]
Tested on kubevirt/kubevirt and it works as expected:
- Given a NAD like:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-spoof-check
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name": "br-spoof-check",
            "type": "cnv-bridge",
            "bridge": "br10",
            "macspoofchk": true
        }'
```
- And a VMI spec pointing to it.

Changing the mac address of the guest results in traffic being blocked.
It has been tested manually by defining two VMI/s with secondary nic/s that share the same NAD.

**Comment by phoracek** [comment]
I have built the images and posted https://github.com/EdDev/cluster-network-addons-operator/pull/1. You can merge it to get it to this branch

**Review by phoracek — APPROVED** [review]
/lgtm

**Comment by RamLavi** [comment]
/approve

thanks for the help @EdDev!

**Pull request merged**
