### PR TITLE
Release 0.53.7

### PR DESCRIPTION
**Pull request by phoracek**
Signed-off-by: Petr Horáček <phoracek@redhat.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
@rhrazdil is this a known flaky?
```
E2E Test Suite: NodeNetworkConfigurationPolicy bonding default interface when there is a default interface with dynamic address should successfully move default IP address on top of the bond


```

**Comment by rhrazdil** [comment]
@RamLavi  IIRC it was a known flaky in knmstate 0.47 

/test pull-e2e-cnao-nmstate-functests-release-0.53

**Pull request merged**
