### PR TITLE
ksd: Add Placement support

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
In order to allow HCO control the KSD placement,
add it to the KSD spec.

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Review by RamLavi — CHANGES_REQUESTED** [review]
please add ksd to the placement ci tests (such as `and workload PlacementConfiguration is deployed on components`)

**Comment by oshoval** [comment]
Done, lets see lane passes

**Comment by oshoval** [comment]
btw not related to this PR but MultusDynamicNetworks doesnt have nodeSelector
maybe because affinity knows to support this as well ?
if so we can remove nodeSelector from all placements, we have it on all components 
beside MultusDynamicNetworks

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1492/pull-e2e-cnao-multus-dynamic-networks-functests/1607358958513688576

doesnt seem related to the PR

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
