### PR TITLE
components, set macvtap as static to v0.5.1

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
set macvtap as static to v0.5.1 in components.yaml

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maiqueb** [comment]
I don't mind lgtm'ing it, but I wonder if we shouldn't bump to[0.6.0](https://github.com/kubevirt/macvtap-cni/releases/tag/v0.6.0) instead, which was released a couple of weeks ago.

**Comment by RamLavi** [comment]
> I don't mind lgtm'ing it, but I wonder if we shouldn't bump to [0.6.0](https://github.com/kubevirt/macvtap-cni/releases/tag/v0.6.0) instead, which was released a couple of weeks ago.
> 
> EDIT: we bump golang from 1.13 to 1.16, and k8s version from 1.19 to 1.20.

according to @phoracek , v0.6.0 mustn't be bumped on this stable branch (see [here](https://github.com/kubevirt/cluster-network-addons-operator/pull/1057))

**Review by maiqueb — APPROVED** [review]
> > I don't mind lgtm'ing it, but I wonder if we shouldn't bump to [0.6.0](https://github.com/kubevirt/macvtap-cni/releases/tag/v0.6.0) instead, which was released a couple of weeks ago.
> > EDIT: we bump golang from 1.13 to 1.16, and k8s version from 1.19 to 1.20.
> 
> according to @phoracek , v0.6.0 mustn't be bumped on this stable branch (see [here](https://github.com/kubevirt/cluster-network-addons-operator/pull/1057))

My bad, I didn't realize this pull request targeted a stable branch. 

Thanks.

**Pull request merged**
