### PR TITLE
ovs: Fix ovs cni bumper and bump ovs-cni

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Since the image repository was changed, the scripts had to be updated.
bump ovs-cni to v0.34.0

**Special notes for your reviewer**:

**Release note**:

```release-note
bump ovs-cni to v0.34.0
```

### CODE REVIEW

**Comment by oshoval** [comment]
/cc @ram @phoracek @qinqon 
can you review please ?

**Comment by oshoval** [comment]
/cc @RamLavi 
ptal

**Review by RamLavi — COMMENTED** [review]
@oshoval don't you want to only fix the script and wait until the auto bumper works? 
It would be a good validation..

**Comment by oshoval** [comment]
> @oshoval don't you want to only fix the script and wait until the auto bumper works? It would be a good validation..

No need, i ran the script manually, to validate it, the script did those changes

**Comment by oshoval** [comment]
soon i am going to fix another thing on OVS and it will then ran the bumper again once there is a new version
https://github.com/k8snetworkplumbingwg/ovs-cni/pull/319

this PR is totally safe imo

**Pull request merged**
