### PR TITLE
[release-0.42] macvtap-cni, update repo main branch

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR updates the components.yaml with macvtap-cni's new main branch

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]

**Comment by RamLavi** [comment]
@qinqon regarding the `pull-cluster-network-addons-operator-unit-test` lane failing - looks like this branch is missing a part f the script. 
I ran unit tests locally and they pass
Since this stable branch is still supported - I'll issue another PR to fix the lane

**Comment by RamLavi** [comment]
/retest
strange, locally I'm not getting the multus issue on `pull-cluster-network-addons-operator-unit-test ` lane.checking flakiness

**Comment by RamLavi** [comment]
/retest
known issue on this version

**Comment by RamLavi** [comment]
/retest
known issue on this version

**Pull request merged**
