### PR TITLE
Use https on runbooks URLs

### PR DESCRIPTION
**Pull request by tiraboschi**
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**What this PR does / why we need it**:

Web browsers are becoming increasingly vocal about
unencrypted links, let's move to
https to prevent unnecessary noise.

**Special notes for your reviewer**:

Only http -> https

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]

**Comment by tiraboschi** [comment]
@oshoval ping

**Comment by oshoval** [comment]
> @oshoval ping

Hi, I lgtmed already, please ask a maintainer to view it

**Comment by tiraboschi** [comment]
@phoracek ping

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
