### PR TITLE
lifecycle: Delete non supported releases

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
When issuing a new release it will make the lane faster, as it wont test releases 
that arent supported anymore.

**Special notes for your reviewer**:
Depends on https://github.com/kubevirt/cluster-network-addons-operator/pull/1869

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
All passed @qinqon @RamLavi 
can you please review ?

**Comment by RamLavi** [comment]
Hey, thank you for this change. Please also update the README with the oldest supported version

**Comment by oshoval** [comment]
> Hey, thank you for this change. Please also update the README with the oldest supported version

was done on the previous PR if thats what you mean
https://github.com/kubevirt/cluster-network-addons-operator/pull/1869/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
