### PR TITLE
[DNM] check KMP master

### PR DESCRIPTION
**Pull request by RamLavi**
DNM

Signed-off-by: Ram Lavi <ralavi@redhat.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by qinqon** [comment]
/retest

kubevirt startup time hiccup
```
kubevirts.kubevirt.io   2021-04-20T12:01:06Z
+ ./cluster/kubectl.sh apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.40.0/kubevirt-cr.yaml
kubevirt.kubevirt.io/kubevirt created
+ count=0
+ ./cluster/kubectl.sh -n kubevirt get kv kubevirt
NAME       AGE   PHASE
kubevirt   1s    
+ ./cluster/kubectl.sh wait -n kubevirt kv kubevirt --for condition=Available --timeout 180s
error: timed out waiting for the condition on kubevirts/kubevirt
+ echo 'KubeVirt not ready in time'
KubeVirt not ready in time
+ exit 1
+ teardown
+ rm -rf /tmp/deploy.kubemacpool.l98z/github.com/k8snetworkplumbingwg/kubemacpool
+ cd /tmp/cnao//cluster-network-addons-operator
+ make cluster-down
./
```

**Comment by RamLavi** [comment]
/test pull-e2e-cluster-network-addons-operator-kubemacpool-functests

second pass, just to be sure.

**Comment by qinqon** [comment]
/retest
new nmstate flaky test ?

**Comment by RamLavi** [comment]
looks good, closing this and issuing a KMP release

**Pull request closed without merging**
