### PR TITLE
DNM: Higher timeout on OVS

### PR DESCRIPTION
**Pull request by phoracek**
Signed-off-by: Petr Horacek <hrck@protonmail.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by RamLavi** [comment]
#2
/test pull-e2e-cluster-network-addons-operator-ovs-cni-functests

**Comment by phoracek** [comment]
/test pull-e2e-cluster-network-addons-operator-ovs-cni-functests

1/1

(Had to restart, -i was missing)

**Comment by phoracek** [comment]
/test pull-e2e-cluster-network-addons-operator-ovs-cni-functests

2/2

**Comment by phoracek** [comment]
/test pull-e2e-cluster-network-addons-operator-ovs-cni-functests

3/3

**Comment by phoracek** [comment]
/cancel

Will fix this on OVS CNI and release a new version.

**Comment by phoracek** [comment]
https://github.com/k8snetworkplumbingwg/ovs-cni/pull/255

**Pull request closed without merging**
