### PR TITLE
[release-0.53] cluster: Enable just ovs repo (#1163)

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
Some openstack repos does not support centos 8 stream yet. This change
point directly to the centos 8 stream ovs repo.

**Special notes for your reviewer**:
(cherry picked from commit 152a52e78f453e766e42fb590207ec4eb90cb3fe)

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by rhrazdil — APPROVED** [review]

**Comment by qinqon** [comment]
Something is not right after bumping kubevirtci 
```
HEAD is now at b05af17 Add fedora kubeadm image for capk (#711)
selecting docker as container runtime
/tmp/deploy.multus.hZZI/github.com/k8snetworkplumbingwg/multus-cni/e2e/_kubevirtci/cluster-up//cluster/ephemeral-provider-common.sh: line 136: /tmp/deploy.multus.hZZI/github.com/k8snetworkplumbingwg/multus-cni/e2e/_kubevirtci/_ci-configs/k8s-1.19/.kubectl: No such file or directory
+ teardown
+ rm -rf /tmp/deploy.multus.hZZI/github.com/k8snetworkplumbingwg/multus-cni
```

**Comment by qinqon** [comment]
Bumping go to 1.16 to resolve:
```
go: github.com/Mellanox/sriovnet@v1.0.2: parse https://proxy.golang.org|https://goproxy.io|direct: invalid character "|" in host name
```

**Review by phoracek — COMMENTED** [review]
/lgtm
/approve

**Comment by qinqon** [comment]
/retest

Kobemacpool is not ready, there is leader election at this version.

**Pull request merged**
