### PR TITLE
bump kubemacpool to v0.20.2

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR bumps kubemacpool to v0.20.2

**Special notes for your reviewer**:

**Release note**:

```release-note
bump kubemacpool to v0.20.2
```

### CODE REVIEW

**Comment by RamLavi** [comment]
/override pull-e2e-cluster-network-addons-operator-kubemacpool-functests

this test fails since tier1 tests should not run `opt-out` context tests. #567 added to fix this.

**Comment by qinqon** [comment]
/override pull-e2e-cluster-network-addons-operator-kubemacpool-functests

**Pull request merged**
