### PR TITLE
tests: remove OKD special configuration

### PR DESCRIPTION
**Pull request by alonSadan**
**What this PR does / why we need it**:
CI never runs on OKD cluster, so no extra care is needed like we had for multus.
This commit removes isOnOKD and everything under it's scope as it is
no longer relevant.

Signed-off-by: alonsadan <asadan@redhat.com>

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
@rhrazdil did you encounter [these](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1004/pull-e2e-cluster-network-addons-operator-nmstate-functests/1433440410822250496) error exceptions before?

**Comment by alonSadan** [comment]
From what I understand this PR affects only multus, and has nothing to do with nmstate failures. 
/retest

**Pull request merged**
