### PR TITLE
kubemacpool: Bump to v0.41.0

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
Latest kubemacpool has some changes that breaks autobumper, this change adapt autobumper and do a manual bump.

```release-note
Bump kubemacpool to v0.41.0
```

### CODE REVIEW

**Comment by oshoval** [comment]
Thanks

./hack/components/bump-kubemacpool.sh: line 122: go: command not found
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1551/pull-cluster-network-addons-operator-unit-test/1658777191237816320

lets also make sure the KMP lane here passes

**Comment by oshoval** [comment]
KMP fails due to 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1551/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1658777191074238464
`+ /tmp/deploy.kubemacpool.oXOQ/github.com/k8snetworkplumbingwg/kubemacpool/build/_output/bin//go//bin//go test ./tests/... --junit-output=/logs/artifacts/junit.functest.xml --ginkgo.skip '\(opt-in\smode\)'
flag provided but not defined: -junit-output`

**Comment by oshoval** [comment]
About pull-e2e-cluster-network-addons-operator-monitoring-k8s  and pull-e2e-cluster-network-addons-operator-workflow-k8s, maybe more changes are needed on CNAO itself / on KMP
lets see once the other problems are fixed in this PR
when I tried to quick and dirty bump the KMP changes (+ do all the other changes to the RBAC on CNAO)
it didn't happen (https://github.com/kubevirt/cluster-network-addons-operator/pull/1550)

**Comment by oshoval** [comment]
Btw maybe lets split this PR to the tool updating and the bumping will be part of https://github.com/kubevirt/cluster-network-addons-operator/pull/1550
this way the problems on workflow and moitoring will be fixed if they are related to the rbac, and it is more accurate
wdyt?

**Comment by oshoval** [comment]
> > Btw maybe lets split this PR to the tool updating and the bumping will be part of #1550 this way the problems on workflow and moitoring will be fixed if they are related to the rbac, and it is more accurate wdyt?
> 
> Let's do that when everything is green, to have proper history

Np but note please that you might need to add few rbacs in this case (there are still other problems beside that in this PR)
In order to know what rbacs are needed, you need to enable audit logs and then check them 
https://github.com/kubevirt/cluster-network-addons-operator/pull/1536
I can help with it if needed of course, thanks

**Comment by qinqon** [comment]
> /hold
> 
> Let's move the Go bump to a different PR

Golang version change is not needed, going back to 1.17

/hold cancel

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
