### PR TITLE
bumper, Add a new bumper workflow for release-0.44

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
In order for the bumper to track and auto bump in the release-0.44 stable branch
we add a new workflow to track it.

**Special notes for your reviewer**:
This PR is pending until the PR to update release-0.44's components file is merged (#728).

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
/hold

This PR is pending until the PR to update release-0.44's components file is merged.

**Review by phoracek — COMMENTED** [review]
/lgtm
/approve

**Comment by RamLavi** [comment]
/override pull-e2e-cluster-network-addons-operator-nmstate-functests 
known [flaky](https://github.com/kubevirt/cluster-network-addons-operator/issues/703), has nothing to do with this PR

**Pull request merged**
