### PR TITLE
0.65: Mark as static components with main

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
At a release branch if a component has not release branch itself it has
to be marked at static at components.yaml so autobumper will ignore new
tags.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by rhrazdil — COMMENTED** [review]
Don't we want to do this change on main branch as well?

**Comment by qinqon** [comment]
> Don't we want to do this change on main branch as well?

Main branch shuld stay with `tagged` so we receive the github-bot PRs bumping components when they release a new tag, then at release branches we "freeze" those version changing with "static" the components that do not have a release branch, problem with that is that is very error prone, now at CNAO creating a release branch involve the following:
- Create the branch itself at git
- Change components.yaml to freeze the ones with release branchs
- Create the prow jobs for that release branch.

**Comment by rhrazdil** [comment]
Got it, thanks!

> Maybe we can start thinking about automatization to create release branches at leat at CNAO.

Yes, that sounds helpful

**Comment by qinqon** [comment]
/override pull-e2e-cnao-workflow-k8s-release-0.65

Not related the policy to static change is only used by the autobumper.

**Pull request merged**
