### PR TITLE
chore: Update dependencies

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Updated following modules to the latest versions:

- golang.org/x/*
- github.com/docker/distribution
- helm.sh/helm/v3
- k8s.io/kubernetes

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
Thanks
note please that `x/net` specifically was done already https://github.com/kubevirt/cluster-network-addons-operator/pull/1617

Please add hold reason if possible

**Comment by RamLavi** [comment]
Hey @0xFelix 
Stupid question: what do you mean by "chore: ... " in the PR title?

**Comment by 0xFelix** [comment]
@oshoval Put this on hold because I need to investigate a bit more on how to properly update the deps in older release branches. Might be necessary to modify parts of the code like it was done for e.g. kubemacpool.

@RamLavi https://www.conventionalcommits.org/en/v1.0.0/ :)

**Pull request closed without merging**
